# QGIS 3.22.16 (latest stable version when QSCAT development started)

name: QSCAT CI

on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -el {0}
        
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
      - name: Install Libmamba
        run: |
          conda config --set solver libmamba
      - name: Install QGIS package from conda-forge
        run: |
          conda install -c conda-forge qgis=3.22.16
      - name: Check environment
        run: |
          conda list
      - name: PyTest
        run: |
          git clone https://github.com/louisfacun/qscat
          pytest qscat/tests