name: Create installable QGIS zip file of QSCAT release
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compress qscat
        run: zip -r qscat.zip qscat/

      - name: Upload qscat zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./qscat.zip
          asset_name: qscat.zip
          asset_content_type: application/zip
