name: QGIS test latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clone QGIS repository
      run: git clone https://github.com/qgis/QGIS.git

    - name: Build the QGIS Docker image
      run: |
        docker build -t qgis/qgis:latest \
         --build-arg DOCKER_TAG=latest \
         -f .docker/qgis.dockerfile \
         .

    - name: Run the QGIS Docker container
      run: |
        docker run -d --name qgis -v /tmp/.X11-unix:/tmp/.X11-unix \
          -v ${{ github.workspace }}/tests/:/tests_directory \
          -e DISPLAY=:99 \
          qgis/qgis:latest

    - name: Ensure pytest is installed
      run: docker exec -it qgis sh -c "pip install pytest"
      
    - name: Run the tests in the Docker QGIS
      run: docker exec -it qgis sh -c "cd /tests_directory && pytest"
